darknet_ros_topic: /darknet_ros/bounding_boxes
output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
point_cloud_topic: /kinect2/hd/points
working_frame: custom_ir_frame
mininum_detection_thereshold: 0.3
minimum_probability: 0.3
interested_classes: ["person", "bottle", "book", "vase", "cup"]
